version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node

      # Builtâ€‘in security (username & password)
      - ELASTIC_PASSWORD=changeme123
      - xpack.security.enabled=true

      # JVM opts (optional)
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-u", "elastic:changeme123", "-f", "http://localhost:9200/_cluster/health"]
      interval: 15s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: kibana
    environment:
      # Tell Kibana how to connect back to Elasticsearch
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=2jH=PyRvif5LYAORwvZ7

      # Optional: expose Kibana publicly (0.0.0.0)
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - kibana_data:/usr/share/kibana/data

volumes:
  es_data:
  kibana_data:
